import flask
import views
import os
import errno

def create_folder(name):
    try:
        os.makedirs(name)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise

global flask_app
flask_app = flask.Flask(__name__, instance_relative_config=True)

flask_app.config.from_object('config')
# https://pythonspot.com/en/flask-web-forms/
# http://flask.pocoo.org/docs/0.12/quickstart/#http-methods
# The secret key shall move out of here to a file which is not in the GIT repository
# and be generated by the setup code
flask_app.secret_key = os.urandom(24).encode('hex')  # flask_app.config['SECRET_KEY'] shall work as well 
UPLOAD_FOLDER = os.path.abspath('./uploads')
flask_app.config.upload_folder = UPLOAD_FOLDER
create_folder(UPLOAD_FOLDER)
flask_app.giphy_api_key = os.environ.get('GIPHY_API_KEY', None)
if not flask_app.giphy_api_key:
    print("No GIPHY API key provided. Try to set GIPHY_API_KEY")
    flask_app.giphy_api_key = "UKNOWN_API_KEY"


@flask_app.errorhandler(404)
def not_found(error):
    flask.flash(error)
    resp = flask.make_response(flask.render_template('error.html', error_code=404), 404)
    resp.headers['X-Something'] = 'A value' # TODO What is it
    return resp

@flask_app.errorhandler(405)
def method_not_allowed(error):
    flask.flash(error)
    resp = flask.make_response(flask.render_template('error.html', error_code=405), 405)
    resp.headers['X-Something'] = 'A value' # TODO What is it
    return resp

views_object = views.Views(flask_app)

